// *** WARNING ***
// File is Autogenerated from KorApp package
// Any modification will be overwritten. 

import 'package:flutter/material.dart';

class {{page_name}}Page extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _{{page_name}}Page();
}

class _{{page_name}}Page extends State<{{page_name}}Page> {

  TextEditingController nameController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('{{page_name}} Page'),
      ),
      body: Padding(
        child: Text('Blank Page'),
        padding: EdgeInsets.only(top: 15.0, left:10.0, right:10.0),
      ),
    );
  }
  
}